spring:
      application:
               name: graphql-todo-app
server:
      port: 9000

graphql:
      servlet:
               mapping: /graphql
               enabled: true
               corsEnabled: false
      spring-graphql-common:
               clientMutationIdName: clientMutationId
               injectClientMutationId: true
               allowEmptyClientMutationId: false
               mutationInputArgumentName: input
               outputObjectNamePrefix: Payload
               inputObjectNamePrefix: Input
               schemaMutationObjectName: Mutation

graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true